#web と redis という 2 つのサービスを定義
version: "3.9"
services:
  #web サービスは、カレントディレクトリ内のDockerfileからビルドされた
  #イメージを利用します。 そしてコンテナーとホストマシンを、
  #公開用ポート8000でつなぎます。 このサービス例では、
  #Flask ウェブサーバーのデフォルトポートである5000を利用するものです。
  web:
    build: .
    ports:
      - "8000:5000"
#ホスト上のプロジェクトディレクトリ（カレントディレクトリ）を、
#コンテナー内にある /code ディレクトリにマウントします。 
#こうすることで、イメージを再構築することなく、
#実行中のコードを修正できるようになります。 
    volumes:
      - .:/code
#environmentキーには環境変数FLASK_ENVを設定しています。
#これは開発モードでflask runを実行し、コード変更時にリロードするよう指示します。 
    environment:
      FLASK_ENV: development
  #redis サービスには Docker Hub レジストリから取得した、
  #公開の Redis イメージを利用します。
  redis:
    image: "redis:alpine"